# fly.toml app configuration file generated for piraquara on 2024-02-02T02:25:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'piraquara'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[[mounts]]
  source="piraquara_db"
  destination="/mnt/piraquara_db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
